all:
	- pdflatex -interaction=nonstopmode -shell-escape hw.tex
	- pdflatex -interaction=nonstopmode -shell-escape hw.tex
	- pdflatex -interaction=nonstopmode -shell-escape hw.tex

install: 
	- apt-get update
	- apt-get install inkscape texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-lang-czechslovak gnuplot

