all:
	- pdflatex -shell-escape hw.tex

install: 
	- apt-get update
	- apt-get install inkscape texlive-full texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-lang-czechslovak latex-xcolor

